## Implementasi Kebijakan Khusus

Selain mengikuti perkuliahan, untuk memastikan adanya transisi yang mulus antara tahun pertama, ketika mayoritas beban mahasiswa masih ada pada perkuliahan, dengan tahun kedua, ketika porsi beban mahasiswa mulai banyak di sisi penelitian, ada beberapa strategi yang diterapkan oleh PMPSTE. Dosen pembimbing berhak mewajibkan mahasiswanya untuk *sit in* pada mata kuliah yang relevan di luar mata kuliah yang telah tersedia pada PMPSTE yang ditawarkan DTETI pada program studi sarjana, baik Teknik Elektro, Teknologi Informasi, atau Teknik Biomedis. Mahasiswa yang *sit in* pada mata kuliah tertentu diwajibkan untuk menghadiri seluruh pertemuan pada perkuliahan secara pasif tanpa harus terlibat aktif dalam penugasan dan ujian. Kebijakan ini dirasa perlu untuk kasus-kasus seperti topik tesis mahasiswa menuntut pemahaman akan konsep keilmuan mendasar yang tidak ditawarkan pada PMPSTE. Untuk memastikan agar mahasiswa tidak terbebani terlalu berat, jumlah mata kuliah *sit in* hanya dibatasi sebanyak tiga mata kuliah per tahun.

Untuk mahasiswa yang mengikuti Kurikulum 2022 Versi Revisi-2, mahasiswa diarahkan untuk mendapatkan topik penelitian tesis pada akhir semester 1 atau awal semester 2. Mahasiswa diwajibkan untuk mengajukan proposal penelitian tesis pada semester 1 yang dikawal oleh Mata Kuliah Metodologi Penelitian dan Proposal Tesis (2 SKS). Proposal ini akan ditelaah oleh tim dosen berdasarkan Kelompok Bidang Keahlian (KBK). Penelaahan proposal ini dilakukan pada akhir semester 1 dan hasilnya akan digunakan KBK untuk menentukan topik penelitian dan dosen pembimbing tesis. Dengan demikian, secara normal mahasiswa akan mendapatkan topik penelitian tesis serta dosen pembimbing pada akhir semester 1 atau awal semester 2.

Sejak semester 2, mahasiswa residen di laboratorium tertentu yang nantinya akan menjadi lokasi penelitian tesisnya di bawah dosen pembimbing tesis. Yang dimaksud dengan residen di sini adalah mahasiswa seintensif mungkin berada di laboratorium dan berdiskusi dengan dosen pembimbing tentang penelitian tesisnya. Kebijakan ini bertujuan agar mahasiswa bisa seawal mungkin berinteraksi dengan dosen pembimbing, membiasakan diri dengan lingkungan dan fasilitas laboratorium, serta terjun lebih awal ke topik penelitian yang diambil. Kemudian, agar beban perkuliahan tidak terlalu padat, Mata Kuliah Seminar 1 dan Seminar 2 diisi aktivitas-aktivitas penunjang penelitian seperti studi literatur, diskusi, dan ditutup dengan kegiatan *post-graduate symposium* (PGS) di mana mahasiswa mempresentasikan topik-topik penelitiannya di depan mahasiswa dan dosen PMPSTE. Kegiatan yang sama juga diselenggarakan sebagai penutup Mata Kuliah Penulisan Publikasi dengan tujuan mahasiswa lebih banyak memperoleh kesempatan untuk mempresentasikan penelitiannya dan mendapatkan masukan.

Program *joint-degree* dan *double-degree* diakomodasi oleh Kurikulum 2022 Versi Revisi-2. Kurikulum ini didesain fleksibel dan akomodatif terhadap kebutuhan-kebutuhan kerja sama pada jenjang magister. Aturan-aturan khusus seperti yang telah ditetapkan di atas membuka peluang kerja sama pendidikan dengan pihak luar secara luas. Dalam hal pengaturan khusus untuk mengakomodasi kerja sama, mata kuliah yang telah ditetapkan dapat disesuaikan materi dan cara penyampaiannya dalam koridor konsistensi capaian CPL, jumlah SKS total yang harus ditempuh, serta syarat kelulusan sebagaimana yang telah ditetapkan pada jenjang yang lebih tinggi. Program studi memiliki derajat kebebasan yang cukup luas untuk merealisasikan kelas *joint* dan *double-degree* selama rambu-rambu tersebut tetap dapat dipertahankan.