## Persyaratan Kelulusan (Yudisium)

Mahasiswa dinyatakan lulus untuk menyandang gelar *Master of Engineering* (M.Eng.) dalam bidang Teknik Elektro apabila telah memenuhi syarat-syarat sebagai berikut.

1.  Memenuhi Peraturan Rektor No. 23 Tahun 2024.

2.  Telah menyelesaikan semua mata kuliah yang disyaratkan oleh program studi sesuai dengan konsentrasi yang diambil.

3.  Telah menyelesaikan paling sedikit 36 (tiga puluh enam) SKS.

4.  IPK minimal 3,00 untuk magister berbasis perkuliahan dan 3,25 untuk magister berbasis penelitian; serta tidak ada nilai D dan E.

5.  Telah menyelesaikan tesis dan ujian tesis.

6.  Menerbitkan publikasi ilmiah sesuai dengan syarat yang ditentukan pada masing-masing skema (berbasis perkuliahan atau berbasis penelitian) untuk topik penelitiannya. Publikasi mahasiswa dinyatakan sah jika naskah publikasi adalah hasil penelitian tesis, dan ditulis dengan penulis mahasiswa dan semua dosen pembimbingnya. Mahasiswa harus menyertakan semua dosen pembimbing sebagai penulis dalam publikasi ilmiah ini dan menyebutkan Departemen Teknik Elektro dan Teknologi Informasi FT UGM sebagai institusinya. Urutan penulis untuk naskah publikasi disepakati oleh para penulis.

7.  Telah memiliki kemampuan berbahasa Inggris yang dinyatakan dengan TOEFL *score* (*Institutional Testing Program* atau *International*) atau TOEFL-*like* *score* (*paper based*) sesuai Peraturan Dekan No. 1 Tahun 2025. Dalam hal menggunakan TOEFL-*like* *score* maka ujian harus diselenggarakan di lingkungan Universitas Gadjah Mada. Bagi yang belum memenuhi syarat, harus mengajukan permohonan proses lanjut  dengan melampirkan naskah publikasi berbahasa Inggris yang telah di-*submit* ke seminar internasional atau editor jurnal minimal jurnal nasional.