## Identitas Prodi

### Perguruan Tinggi

#### Nama {.unnumbered}

Universitas Gadjah Mada

#### Visi {.unnumbered}

Sebagai pelopor perguruan tinggi nasional berkelas dunia yang unggul dan inovatif, mengabdi kepada kepentingan bangsa dan kemanusiaan, dijiwai nilai-nilai budaya bangsa berdasarkan Pancasila.

#### Misi {.unnumbered}

Melaksanakan pendidikan, penelitian, dan pengabdian kepada masyarakat serta pelestarian dan pengembangan ilmu yang unggul dan bermanfaat bagi masyarakat.

#### Tujuan {.unnumbered}

Tujuan jangka panjang UGM adalah sebagai berikut:

a.  Mewujudkan UGM sebagai lembaga nasional ilmu pengetahuan,  kebudayaan, dan pendidikan tinggi yang menanamkan dan mengajarkan ilmu pengetahuan dan kebudayaan.

b.  Membentuk manusia susila yang mempunyai keinsafan serta bertanggung jawab terhadap kesejahteraan Indonesia pada khususnya dan dunia pada umumnya. Lima jati diri UGM yang meliputi:

    a.  universitas nasional;

    b.  universitas kerakyatan;

    c.  universitas Pancasila;

    d.  universitas perjuangan; dan

    e.  universitas pusat kebudayaan;

perlu terus termanifestasi dalam pemikiran, sikap, dan perilaku sivitas akademika UGM dalam mencapai visi, misi, dan tujuan. Oleh karena itu, UGM berkomitmen untuk terus memperkuat jati diri serta menerjemahkannya dalam konteks terkini. Jati diri inilah yang akan terus menjadi pedoman dalam menghadapi turbulensi zaman dan perubahan-perubahan besar yang berlangsung.

\*Berdasar dokumen Rencana Strategis Universitas Gadjah Mada Tahun 2022-2027

### Fakultas {#sec-faculty}

#### Nama {.unnumbered}

Fakultas Teknik

#### Visi {.unnumbered}

Fakultas Teknik UGM menjadi lembaga pendidikan tinggi teknik berjejaring nasional dan global untuk penguatan peradaban baru, penguatan kemandirian dan kedaulatan bangsa di bidang IPTEK, dan perlambatan kenaikan entropi dunia, dalam rangka mengabdi kepada kepentingan bangsa dan kemanusiaan yang dijiwai oleh nilai-nilai budaya bangsa berdasarkan Pancasila.

#### Misi {.unnumbered}

Melaksanakan pendidikan, penelitian, dan pengabdian kepada masyarakat serta pelestarian dan pengembangan ilmu pengetahuan dan teknologi berbasis riset dan budaya bangsa yang unggul dan bermanfaat bagi masyarakat.

a.  Menyelenggarakan pendidikan untuk menghasilkan manusia beretika dan mumpuni di bidang ilmu pengetahuan dan teknik yang berdaya guna dan mengabdi untuk kepentingan bangsa dan kemanusiaan.

b.  Mengembangkan, menyebarluaskan, dan melestarikan ilmu pengetahuan dan teknik untuk kepentingan bangsa dan kemanusiaan.

c.  Menumbuhkan dan mengembangkan kreativitas dan melaksanakan pengabdian kepada masyarakat yang berlandaskan budaya bangsa.

d.  Mengembangkan kerja sama yang luas dengan lembaga di dalam dan di luar negeri.

e.  Menjalankan tata kelola organisasi yang *agile,* dan memenuhi kriteria *good governance*

#### Tujuan {.unnumbered}

Mewujudkan Fakultas Teknik UGM sebagai lembaga pendidikan tinggi teknik bertaraf internasional yang unggul, inovatif dan bermartabat melalui: a. Menghasilkan lulusan yang unggul, inovatif dan humanis berakhlak mulia dengan menanamkan dan mengajarkan ilmu pengetahuan dan teknologi yang dilandasi nilai-nilai kearifan dan kebudayaan untuk memuliakan kemanusiaan dan peradaban bangsa yang maju sesuai cita-cita Proklamasi Kemerdekaan Republik Indonesia.

b.  Menghasilkan karya penelitian ilmu pengetahuan dan teknologi yang menjadi rujukan nasional dan internasional.

c.  Menghasilkan dan menyebarluaskan karya teknologi yang menjawab kebutuhan masyarakat dan berkontribusi dalam membangun kedaulatan bangsa dan negara serta pembangunan berkelanjutan.

d.  Meningkatkan kemandirian dan kesejahteraan masyarakat yang berkelanjutan melalui pemberdayaan dan pengabdian kepada masyarakat.

e.  Meningkatkan sinergi korsa dan kehidupan warga Fakultas Teknik UGM yang sehat, sejahtera dan bahagia melalui tata kelola yang sehat dan harmonis.

f.  Membangun kerja sama saling menguntungkan dengan alumni, para pemangku kepentingan, dan mitra di dalam dan luar negeri untuk kemajuan dan kemaslahatan bersama

### Departemen

#### Nama {.unnumbered}

Departemen Teknik Elektro dan Teknologi Informasi

#### Visi {.unnumbered}

Departemen Teknik Elektro dan Teknologi Informasi menjadi sumber inovasi universal di bidang teknik elektro, informasi, dan biomedis untuk kepentingan bangsa dan kemanusiaan yang dijiwai nilai-nilai budaya bangsa berdasarkan Pancasila.

#### Misi {.unnumbered}

a.  Melaksanakan tridarma perguruan tinggi yang mampu menginternalisasi nilai-nilai DTETI (*excellent, teamwork, harmony, optimistic, smart,* dan berintegritas: ETHOS *for integrity*) bagi kepentingan bangsa dan kemanusiaan.
b.  Mengembangkan lingkungan keilmuan yang mendorong tumbuhnya inovasi dalam pelaksanaan tridarma perguruan tinggi.

#### Tujuan {.unnumbered}

a.  Mewujudkan DTETI sebagai penyelenggara pendidikan di bidang teknik elektro, informasi, dan biomedis melalui program sarjana dan pascasarjana yang berkualitas, dalam rangka menghasilkan lulusan yang memiliki kompetensi tinggi, berkarakter dan berintegritas.

b.  Mengembangkan penelitian yang berkontribusi pada pengembangan keilmuan di bidang teknik elektro, informasi, dan biomedis untuk kepentingan bangsa Indonesia dan kemanusiaan secara universal.

c.  Menyelenggarakan pengabdian kepada masyarakat yang berkontribusi secara aktif dalam usaha penyelesaian berbagai masalah bangsa dan kemanusiaan secara universal melalui penyebaran dan penerapan produk-produk keilmuan di bidang teknik elektro, informasi, dan biomedis.

d.  Menjalin kerja sama yang strategis, sinergis, dan berkelanjutan dengan para mitra dalam rangka mendorong tumbuhnya keunggulan dan inovasi dalam pelaksanaan tridarma Perguruan Tinggi.

e.  Menyelenggarakan tata kelola Departemen yang berkeadilan, transparan, partisipatif, akuntabel, dan terintegrasi antar bidang guna menunjang efektivitas dan efisiensi pemanfaatan sumber daya.

### Program Studi

#### Nama {.unnumbered}

Program Magister Program Studi Teknik Elektro (PMPSTE)

#### Visi {.unnumbered}

Visi PMPSTE adalah menjadi sumber inovasi yang universal di bidang ilmu teknik elektro untuk kepentingan bangsa dan kemanusiaan dijiwai nilai-nilai bangsa berdasarkan Pancasila.

#### Misi {.unnumbered}

Misi PMPSTE adalah melaksanakan Tri Dharma Perguruan Tinggi untuk mencetak lulusan yang cakap dan berintegritas dan menghasilkan penelitian yang dapat dimanfaatkan bagi kepentingan bangsa dan kemanusiaan.

#### Tujuan {.unnumbered}

Menjadikan PMPSTE sebagai sumber inovasi dan keunggulan dalam bidang ilmu teknik elektro melalui: a. pengembangan pendidikan di bidang teknik elektro yang berkualitas dalam rangka menghasilkan lulusan yang memiliki kompetensi tinggi, berkarakter, dan berintegritas,

b.  pengembangan penelitian yang berkontribusi pada pengembangan keilmuan bidang teknik elektro untuk kepentingan bangsa Indonesia dan kemanusiaan secara universal,

c.  berkontribusi secara aktif dalam usaha penyelesaian masalah bangsa dan kemanusiaan secara universal melalui penyebaran dan penerapan produk-produk keilmuan dalam bidang teknik elektro,

d.  pengembangan lingkungan akademik yang mendorong tumbuhnya keunggulan dan inovasi dalam pelaksanaan Tri Dharma Perguruan Tinggi.

### Akreditasi

Program Magister Program Studi Teknik Elektro sejak 23 Mei 2023 sampai dengan 1 November 2025 terakreditasi dengan peringkat Unggul berdasarkan keputusan Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT) nomor 1913/SK/BAN-PT/Ak.KP/M/V/2023.

a.  Jenjang Pendidikan

Jenjang pendidikan dari kurikulum ini adalah tingkat magister.

b.  Gelar Lulusan

Gelar lulusan yang akan diberikan adalah Master of Engineering (M.Eng.). Gelar ini diberikan berdasarkan Keputusan Rektor Universitas Gadjah Mada Nomor 292/P/SK/HT/2008 dan 364/P/SK/HT/2009. Lulusan program magister Teknik Elektro dapat berperan sebagai akademisi dan/atau peneliti yang kompeten di bidangnya, mampu bekerja secara individu maupun dalam tim, menjunjung tinggi etika ilmiah, serta memiliki semangat belajar sepanjang hayat. Mereka juga diharapkan memiliki jiwa kepemimpinan, etika profesional, dan komitmen terhadap pembelajaran seumur hidup di institusi pendidikan seperti universitas, politeknik, atau institut. Selain itu, lulusan dapat berkarier sebagai profesional yang mampu menyelesaikan permasalahan industri dengan pendekatan ilmiah dan terstruktur, serta mampu mengomunikasikan ide secara efektif. Mereka dapat bekerja secara individu atau tim, dan mampu memadukan aspek teknis Teknik Elektro dengan aspek manajemen dalam mendukung pencapaian tujuan institusi tempat mereka bekerja.