## Tujuan Pengajuan Kurikulum

Kurikulum ini diajukan guna mengakomodasi berbagai perubahan yang terjadi dalam rentang lima tahun sejak Kurikulum 2017 dan dua tahun sejak Kurikulum 2022 hingga saat ini. Penyelarasan terjadi atas alasan filosofis, sosiologis, psikologis, historis, hingga yuridis. Dasar-dasar aturan yang digunakan untuk menyesuaikan antara lain KKNI dan SN-Dikti. Poin-poin perbaikan juga dipandu oleh analisis SWOT. Semuanya akan bermuara pada aspek administratif yang tertuang dalam struktur perkuliahan, detail silabus, dan luaran pembelajaran yang diharapkan. Beberapa perbedaan pokok Kurikulum 2022 Versi Revisi-2 dengan Kurikulum 2022 antara lain:

a.  Jumlah SKS pada Kurikulum 2022 sejumlah 40 SKS menjadi 36 SKS.

b.  penambahan jalur PMPSTE-Berbasis Perkuliahan dan Penelitian yang mengakomodasi kerja sama dengan institusi lain,

c.  penguatan kegiatan penelitian, penulisan, dan publikasi ilmiah untuk memperkuat kemampuan penyebarluasan hasil penelitian mahasiswa PMPSTE,

d.  pembaruan mata kuliah pilihan yang diselaraskan dengan perkembangan di bidang teknik elektro dan mata kuliah wajib fakultas sebagaimana dituangkan dalam Peraturan Dekan Fakultas Teknik Universitas Gadjah Mada No. 1 Tahun 2025 tentang Pendidikan Program Pascasarjana.